{% set name = "vowpalwabbit" %}
{% set version = "9.0.0" %}
{% set commit = "bc9ddfd" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/VowpalWabbit/vowpal_wabbit/archive/{{ commit }}.tar.gz  
    sha256: d109f5326e4490d110abcd1c9126ec5f6e6ddaca14780aaad9864347e90bdccb
    patches:
      - turn_off_sse2_flags.diff  # [osx and (build_platform != target_platform)]
build:
  number: 0
  skip: true  # [win]
  string: dev_{{ commit }}_py{{ CONDA_PY }}h{{ PKG_HASH }}_{{ PKG_BUILDNUM }}
  script:
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DRAPIDJSON_SYS_DEP=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DFMT_SYS_DEP=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DSPDLOG_SYS_DEP=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DBUILD_FLATBUFFERS=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DVW_INSTALL=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DBUILD_TESTS=On"
     - export CMAKE_ARGS_EXTRA="$CMAKE_ARGS_EXTRA -DCMAKE_INSTALL_PREFIX=${PREFIX}"
     - sed -i.bak '/\"--build\"/a\ \ \ \ \ \ \ \ \ \ \ \ \self.spawn(["make", "install", "-j{}".format(multiprocessing.cpu_count())])' setup.py
     - sed -i.bak 's/\"pylibvw\"\]/ \"pylibvw\"\, \"vw-bin\"\, \"spanning_tree\"\]/g' setup.py
     - sed -i.bak 's/\"pylibvw\"\,/ \"pylibvw\"\, \"vw-bin\"\, \"spanning_tree\"\,/g' setup.py
     - export CMAKE_ARGS_IN=$(echo $CMAKE_ARGS_EXTRA | sed 's/ /;/g')
     - {{ PYTHON }} setup.py --cmake-options=$CMAKE_ARGS_IN install
     # - {{ PYTHON }} -m pip install . -vv
     # - make install -j{{ CPU_COUNT }}
     
requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - flatbuffers                            # [build_platform != target_platform]
    - rapidjson                              # [build_platform != target_platform]
    - fmt                                    # [build_platform != target_platform]
    - spdlog                                 # [build_platform != target_platform]
    - zlib                                   # [build_platform != target_platform]
    - cmake >=3.13
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - git
  host:
    - pip
    - python
    - boost
    - boost-cpp
    - tox
    - zlib
    - flatbuffers
    - rapidjson
    - fmt
    - spdlog
  run:
    - python
    - boost
    - boost-cpp
    - zlib
    - flatbuffers
    - rapidjson
    - fmt
    - spdlog

test:
  imports:
    - vowpalwabbit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/VowpalWabbit/vowpal_wabbit
  summary: Vowpal Wabbit Python package
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jackgerrits
    - gramhagen
    - peterychang
    - xhochy
    - ngam
